---
title: "Bottleneck Counter Effects"
keep_md: no
author: "Ryan Ward"
date: '2022-05-02'
output: html_document
---
```{r Read files and prepare framework for analyis}
library(pacman)

p_load(data.table, viridis, tidyverse, hrbrthemes, statmod, tidyverse, scales, rmarkdown, gtools, R.utils)

# reads
aba.counts <- fread(
	"overall_counts_with_metadata.tsv.gz",
	header = TRUE)
	# col.names = c("spacer", "count", "condition"))

glimpse(aba.counts)

# guide design key
aba.key <- fread("aba_key.tsv")

glimpse(aba.key)

# experimental design
aba.design <- fread("all_experimental_design.tsv")

glimpse(aba.design)


# hand-curated names with references available
curated_names <- fread("curated_names.tsv")

glimpse(curated_names)

```

```{r Combine, message=FALSE}
aba.genome <- aba.key %>% 
	group_by(locus_tag) %>% 
	select(
		locus_tag,
		spacer, 
		type, 
		y_pred, 
		target, 
		offset) %>% 
	inner_join(
		curated_names, 
		by = c("locus_tag" = "AB19606")) %>% 
	rename(AB19606 = locus_tag)

# define the experimental design space to only take into consideration "tubes"
aba.design <- aba.design %>%
	filter(experiment == "tube") %>% 
	rename(condition = sample)

# keep only the counts that are in the experimental design space
aba.counts <- aba.counts %>% semi_join(aba.design)

# convert single column into a table 
aba.counts <- aba.counts %>% 
	pivot_wider(
		id_cols = spacer, 
		names_from = condition, 
		values_from = count, 
		values_fill = 0) %>%
	pivot_longer(
		!spacer, 
		names_to = "condition", 
		values_to = "count")
```

build up components of bottlenecking calculation
```{r message=FALSE}
# https://www.nature.com/articles/nmeth.3253
aba.design <- aba.design %>% 
	mutate (generations = case_when(
		timing == "T0" ~ 0,
		timing == "T1" ~ 9, 
		timing == "T2" ~ 18))

aba.counts.verbose <- aba.counts %>%
	inner_join(aba.design) %>% 
	inner_join(aba.key) %>%
	mutate(batch = paste0("(", batch, ")")) %>%
	unite("Sample", verbose, timing, rep, batch, sep = " ") %>% 
	select(condition, type, spacer, count, Sample, generations)

aba.botneck.t0 <- aba.counts.verbose %>% 
	filter(generations == 0) %>% 
	group_by(type, spacer) %>% 
	summarise(count = median(count)) %>%
	ungroup(spacer) %>%
	group_by(type) %>%
	mutate(
		fi0 = count/sum(count),
		count0 = count) %>%
	select(type, spacer, fi0, count0) %>%
	nest %>%
	rename(data0 = data) %>%
	mutate(s0 = map_dbl(data0, ~sum(.$count0)))

aba.botneck <- aba.counts.verbose %>%
	filter(generations != 0) %>%
	group_by(type, condition, Sample, generations) %>%
	mutate(
		fis = count/sum(count)) %>%
	nest %>%
		mutate(
		ss = map_dbl(data, ~sum(.$count))) %>% 
	full_join(aba.botneck.t0) %>% 
	mutate(data = map2(data, data0, inner_join))

aba.botneck <- aba.botneck %>% 
	mutate(
		data = map(
			data, ~.x %>% 
				mutate(
					ratio = ( (fis - fi0)^2) / ( fi0 * (1 - fi0)^2 ) )	) )

aba.botneck <- aba.botneck %>% 
	mutate(
		f_hat = map_dbl(
			data, 
			~sum(.$ratio)) * (1 / map_dbl(data, ~n_distinct(.$spacer))),
		Nb = generations/(f_hat - 1/s0 - 1/ss))
```
Bottleneck metric on integer scale.

```{r, fig.width=10, fig.height=5}
aba.botneck.plot <- aba.botneck %>%
	ggplot(aes(
		x = Sample, 
		y = Nb, 
		fill = type)) +
	geom_bar(
		stat = "identity", 
		position = position_dodge(),
		colour = "black") +
	theme_ipsum() + 
	scale_fill_viridis(discrete = T, direction = -1, option = 'cividis') +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
	ggtitle("Population Complexity: Bottleneck Metric") +
	scale_y_continuous(labels = label_number(scale_cut = cut_short_scale()))

print(aba.botneck.plot)

aba.botneck.plot <- aba.botneck %>%
	ggplot(aes(
		x = Sample, 
		y = Nb, 
		fill = type)) +
	geom_bar(
		stat = "identity", 
		position = position_dodge(),
		colour = "black") +
	theme_ipsum() + 
	scale_fill_viridis(discrete = T, direction = -1, option = 'cividis') +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
	ggtitle("Population Complexity: Bottleneck Metric") +
	scale_y_continuous(
					trans = "log10",
					breaks = c(0, 10^seq(0,7)),
					labels = label_number(scale_cut = cut_short_scale()))

print(aba.botneck.plot)
```

Bottleneck numbers (Nb) by condition and type
```{r message=FALSE, warning=FALSE}
aba.botneck %>% 
	select(Nb) %>%
	arrange(mixedsort(Sample)) %>%
	arrange(type) %>%
	pivot_wider(
		names_from = type, 
		values_from = Nb) %>% 
	paged_table
```
